package ec2instances

// Specs holds hardware specifications for an EC2 instance type.
type Specs struct {
	VCPUs       int     `json:"vcpus"`
	MemoryGiB   float64 `json:"memory_gib"`
	NetworkGbps string  `json:"network_gbps"`
	Arch        string  `json:"arch"`
}

// Lookup returns the specs for the given EC2 instance type, or nil if not
// found in the static table. The table is generated by
// tools/update-ec2-instances and should be periodically refreshed.
func Lookup(instanceType string) *Specs {
	if s, ok := table[instanceType]; ok {
		return &s
	}
	return nil
}
