// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/infracost/proto/gen/go/infracost/provider"
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc"
)

// NewMockProviderServiceClient creates a new instance of MockProviderServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProviderServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProviderServiceClient {
	mock := &MockProviderServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProviderServiceClient is an autogenerated mock type for the ProviderServiceClient type
type MockProviderServiceClient struct {
	mock.Mock
}

type MockProviderServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProviderServiceClient) EXPECT() *MockProviderServiceClient_Expecter {
	return &MockProviderServiceClient_Expecter{mock: &_m.Mock}
}

// ListFinopsPolicies provides a mock function for the type MockProviderServiceClient
func (_mock *MockProviderServiceClient) ListFinopsPolicies(ctx context.Context, in *provider.ListFinopsPoliciesRequest, opts ...grpc.CallOption) (*provider.ListFinopsPoliciesResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListFinopsPolicies")
	}

	var r0 *provider.ListFinopsPoliciesResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *provider.ListFinopsPoliciesRequest, ...grpc.CallOption) (*provider.ListFinopsPoliciesResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *provider.ListFinopsPoliciesRequest, ...grpc.CallOption) *provider.ListFinopsPoliciesResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*provider.ListFinopsPoliciesResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *provider.ListFinopsPoliciesRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProviderServiceClient_ListFinopsPolicies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFinopsPolicies'
type MockProviderServiceClient_ListFinopsPolicies_Call struct {
	*mock.Call
}

// ListFinopsPolicies is a helper method to define mock.On call
//   - ctx context.Context
//   - in *provider.ListFinopsPoliciesRequest
//   - opts ...grpc.CallOption
func (_e *MockProviderServiceClient_Expecter) ListFinopsPolicies(ctx interface{}, in interface{}, opts ...interface{}) *MockProviderServiceClient_ListFinopsPolicies_Call {
	return &MockProviderServiceClient_ListFinopsPolicies_Call{Call: _e.mock.On("ListFinopsPolicies",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockProviderServiceClient_ListFinopsPolicies_Call) Run(run func(ctx context.Context, in *provider.ListFinopsPoliciesRequest, opts ...grpc.CallOption)) *MockProviderServiceClient_ListFinopsPolicies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *provider.ListFinopsPoliciesRequest
		if args[1] != nil {
			arg1 = args[1].(*provider.ListFinopsPoliciesRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockProviderServiceClient_ListFinopsPolicies_Call) Return(listFinopsPoliciesResponse *provider.ListFinopsPoliciesResponse, err error) *MockProviderServiceClient_ListFinopsPolicies_Call {
	_c.Call.Return(listFinopsPoliciesResponse, err)
	return _c
}

func (_c *MockProviderServiceClient_ListFinopsPolicies_Call) RunAndReturn(run func(ctx context.Context, in *provider.ListFinopsPoliciesRequest, opts ...grpc.CallOption) (*provider.ListFinopsPoliciesResponse, error)) *MockProviderServiceClient_ListFinopsPolicies_Call {
	_c.Call.Return(run)
	return _c
}

// Process provides a mock function for the type MockProviderServiceClient
func (_mock *MockProviderServiceClient) Process(ctx context.Context, in *provider.ProcessRequest, opts ...grpc.CallOption) (*provider.ProcessResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Process")
	}

	var r0 *provider.ProcessResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *provider.ProcessRequest, ...grpc.CallOption) (*provider.ProcessResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *provider.ProcessRequest, ...grpc.CallOption) *provider.ProcessResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*provider.ProcessResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *provider.ProcessRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProviderServiceClient_Process_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Process'
type MockProviderServiceClient_Process_Call struct {
	*mock.Call
}

// Process is a helper method to define mock.On call
//   - ctx context.Context
//   - in *provider.ProcessRequest
//   - opts ...grpc.CallOption
func (_e *MockProviderServiceClient_Expecter) Process(ctx interface{}, in interface{}, opts ...interface{}) *MockProviderServiceClient_Process_Call {
	return &MockProviderServiceClient_Process_Call{Call: _e.mock.On("Process",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockProviderServiceClient_Process_Call) Run(run func(ctx context.Context, in *provider.ProcessRequest, opts ...grpc.CallOption)) *MockProviderServiceClient_Process_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *provider.ProcessRequest
		if args[1] != nil {
			arg1 = args[1].(*provider.ProcessRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockProviderServiceClient_Process_Call) Return(processResponse *provider.ProcessResponse, err error) *MockProviderServiceClient_Process_Call {
	_c.Call.Return(processResponse, err)
	return _c
}

func (_c *MockProviderServiceClient_Process_Call) RunAndReturn(run func(ctx context.Context, in *provider.ProcessRequest, opts ...grpc.CallOption) (*provider.ProcessResponse, error)) *MockProviderServiceClient_Process_Call {
	_c.Call.Return(run)
	return _c
}
