package main

import (
	"context"
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/ec2"
)

const outputPath = "internal/ec2instances/table.go"

func main() {
	ctx := context.Background()

	region := os.Getenv("AWS_REGION")
	if region == "" {
		region = "us-east-1"
	}

	cfg, err := config.LoadDefaultConfig(ctx, config.WithRegion(region))
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error loading AWS config: %v\n", err)
		os.Exit(1)
	}

	client := ec2.NewFromConfig(cfg)

	type entry struct {
		VCPUs     int
		MemoryGiB float64
		Network   string
		Arch      string
	}

	entries := make(map[string]entry)

	var nextToken *string
	for {
		resp, err := client.DescribeInstanceTypes(ctx, &ec2.DescribeInstanceTypesInput{
			NextToken:  nextToken,
			MaxResults: int32Ptr(100),
		})
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error describing instance types: %v\n", err)
			os.Exit(1)
		}

		for _, info := range resp.InstanceTypes {
			name := string(info.InstanceType)

			var vcpus int
			if info.VCpuInfo != nil && info.VCpuInfo.DefaultVCpus != nil {
				vcpus = int(*info.VCpuInfo.DefaultVCpus)
			}

			var memGiB float64
			if info.MemoryInfo != nil && info.MemoryInfo.SizeInMiB != nil {
				memGiB = float64(*info.MemoryInfo.SizeInMiB) / 1024.0
			}

			var network string
			if info.NetworkInfo != nil && info.NetworkInfo.NetworkPerformance != nil {
				network = normalizeNetworkPerformance(*info.NetworkInfo.NetworkPerformance)
			}

			arch := "x86_64"
			if info.ProcessorInfo != nil {
				for _, a := range info.ProcessorInfo.SupportedArchitectures {
					if string(a) == "arm64" {
						arch = "arm64"
						break
					}
				}
			}

			entries[name] = entry{
				VCPUs:     vcpus,
				MemoryGiB: memGiB,
				Network:   network,
				Arch:      arch,
			}
		}

		nextToken = resp.NextToken
		if nextToken == nil {
			break
		}
	}

	// Sort instance type names for deterministic output.
	names := make([]string, 0, len(entries))
	for name := range entries {
		names = append(names, name)
	}
	sort.Strings(names)

	var b strings.Builder
	b.WriteString("// Code generated by tools/update-ec2-instances. DO NOT EDIT.\n\n")
	b.WriteString("package ec2instances\n\n")
	b.WriteString("var table = map[string]Specs{\n")
	for _, name := range names {
		e := entries[name]
		fmt.Fprintf(&b, "\t%q: {VCPUs: %d, MemoryGiB: %g, NetworkGbps: %q, Arch: %q},\n",
			name, e.VCPUs, e.MemoryGiB, e.Network, e.Arch)
	}
	b.WriteString("}\n")

	if err := os.WriteFile(outputPath, []byte(b.String()), 0600); err != nil {
		fmt.Fprintf(os.Stderr, "Error writing %s: %v\n", outputPath, err)
		os.Exit(1)
	}

	fmt.Fprintf(os.Stderr, "Wrote %d instance types to %s\n", len(entries), outputPath)
}

func normalizeNetworkPerformance(s string) string {
	s = strings.ReplaceAll(s, " Gigabit", "")
	s = strings.ToLower(s)
	return s
}

func int32Ptr(v int32) *int32 {
	return &v
}