// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/infracost/proto/gen/go/infracost/parser/api"
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc"
)

// NewMockParserServiceClient creates a new instance of MockParserServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockParserServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockParserServiceClient {
	mock := &MockParserServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockParserServiceClient is an autogenerated mock type for the ParserServiceClient type
type MockParserServiceClient struct {
	mock.Mock
}

type MockParserServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockParserServiceClient) EXPECT() *MockParserServiceClient_Expecter {
	return &MockParserServiceClient_Expecter{mock: &_m.Mock}
}

// Initialize provides a mock function for the type MockParserServiceClient
func (_mock *MockParserServiceClient) Initialize(ctx context.Context, in *api.InitializeRequest, opts ...grpc.CallOption) (*api.InitializeResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Initialize")
	}

	var r0 *api.InitializeResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *api.InitializeRequest, ...grpc.CallOption) (*api.InitializeResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *api.InitializeRequest, ...grpc.CallOption) *api.InitializeResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.InitializeResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *api.InitializeRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockParserServiceClient_Initialize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Initialize'
type MockParserServiceClient_Initialize_Call struct {
	*mock.Call
}

// Initialize is a helper method to define mock.On call
//   - ctx context.Context
//   - in *api.InitializeRequest
//   - opts ...grpc.CallOption
func (_e *MockParserServiceClient_Expecter) Initialize(ctx interface{}, in interface{}, opts ...interface{}) *MockParserServiceClient_Initialize_Call {
	return &MockParserServiceClient_Initialize_Call{Call: _e.mock.On("Initialize",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockParserServiceClient_Initialize_Call) Run(run func(ctx context.Context, in *api.InitializeRequest, opts ...grpc.CallOption)) *MockParserServiceClient_Initialize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *api.InitializeRequest
		if args[1] != nil {
			arg1 = args[1].(*api.InitializeRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockParserServiceClient_Initialize_Call) Return(initializeResponse *api.InitializeResponse, err error) *MockParserServiceClient_Initialize_Call {
	_c.Call.Return(initializeResponse, err)
	return _c
}

func (_c *MockParserServiceClient_Initialize_Call) RunAndReturn(run func(ctx context.Context, in *api.InitializeRequest, opts ...grpc.CallOption) (*api.InitializeResponse, error)) *MockParserServiceClient_Initialize_Call {
	_c.Call.Return(run)
	return _c
}

// Parse provides a mock function for the type MockParserServiceClient
func (_mock *MockParserServiceClient) Parse(ctx context.Context, in *api.ParseRequest, opts ...grpc.CallOption) (*api.ParseResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 *api.ParseResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *api.ParseRequest, ...grpc.CallOption) (*api.ParseResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *api.ParseRequest, ...grpc.CallOption) *api.ParseResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.ParseResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *api.ParseRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockParserServiceClient_Parse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parse'
type MockParserServiceClient_Parse_Call struct {
	*mock.Call
}

// Parse is a helper method to define mock.On call
//   - ctx context.Context
//   - in *api.ParseRequest
//   - opts ...grpc.CallOption
func (_e *MockParserServiceClient_Expecter) Parse(ctx interface{}, in interface{}, opts ...interface{}) *MockParserServiceClient_Parse_Call {
	return &MockParserServiceClient_Parse_Call{Call: _e.mock.On("Parse",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockParserServiceClient_Parse_Call) Run(run func(ctx context.Context, in *api.ParseRequest, opts ...grpc.CallOption)) *MockParserServiceClient_Parse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *api.ParseRequest
		if args[1] != nil {
			arg1 = args[1].(*api.ParseRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockParserServiceClient_Parse_Call) Return(parseResponse *api.ParseResponse, err error) *MockParserServiceClient_Parse_Call {
	_c.Call.Return(parseResponse, err)
	return _c
}

func (_c *MockParserServiceClient_Parse_Call) RunAndReturn(run func(ctx context.Context, in *api.ParseRequest, opts ...grpc.CallOption) (*api.ParseResponse, error)) *MockParserServiceClient_Parse_Call {
	_c.Call.Return(run)
	return _c
}

// ParseToTree provides a mock function for the type MockParserServiceClient
func (_mock *MockParserServiceClient) ParseToTree(ctx context.Context, in *api.ParseToTreeRequest, opts ...grpc.CallOption) (*api.ParseToTreeResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ParseToTree")
	}

	var r0 *api.ParseToTreeResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *api.ParseToTreeRequest, ...grpc.CallOption) (*api.ParseToTreeResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *api.ParseToTreeRequest, ...grpc.CallOption) *api.ParseToTreeResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.ParseToTreeResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *api.ParseToTreeRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockParserServiceClient_ParseToTree_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseToTree'
type MockParserServiceClient_ParseToTree_Call struct {
	*mock.Call
}

// ParseToTree is a helper method to define mock.On call
//   - ctx context.Context
//   - in *api.ParseToTreeRequest
//   - opts ...grpc.CallOption
func (_e *MockParserServiceClient_Expecter) ParseToTree(ctx interface{}, in interface{}, opts ...interface{}) *MockParserServiceClient_ParseToTree_Call {
	return &MockParserServiceClient_ParseToTree_Call{Call: _e.mock.On("ParseToTree",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockParserServiceClient_ParseToTree_Call) Run(run func(ctx context.Context, in *api.ParseToTreeRequest, opts ...grpc.CallOption)) *MockParserServiceClient_ParseToTree_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *api.ParseToTreeRequest
		if args[1] != nil {
			arg1 = args[1].(*api.ParseToTreeRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockParserServiceClient_ParseToTree_Call) Return(parseToTreeResponse *api.ParseToTreeResponse, err error) *MockParserServiceClient_ParseToTree_Call {
	_c.Call.Return(parseToTreeResponse, err)
	return _c
}

func (_c *MockParserServiceClient_ParseToTree_Call) RunAndReturn(run func(ctx context.Context, in *api.ParseToTreeRequest, opts ...grpc.CallOption) (*api.ParseToTreeResponse, error)) *MockParserServiceClient_ParseToTree_Call {
	_c.Call.Return(run)
	return _c
}
