// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/infracost/cli/internal/api/agents"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// CreateAction provides a mock function for the type MockClient
func (_mock *MockClient) CreateAction(ctx context.Context, orgID string, findingID string, req agents.CreateActionRequest) (agents.CreateActionResponse, error) {
	ret := _mock.Called(ctx, orgID, findingID, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateAction")
	}

	var r0 agents.CreateActionResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, agents.CreateActionRequest) (agents.CreateActionResponse, error)); ok {
		return returnFunc(ctx, orgID, findingID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, agents.CreateActionRequest) agents.CreateActionResponse); ok {
		r0 = returnFunc(ctx, orgID, findingID, req)
	} else {
		r0 = ret.Get(0).(agents.CreateActionResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, agents.CreateActionRequest) error); ok {
		r1 = returnFunc(ctx, orgID, findingID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_CreateAction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAction'
type MockClient_CreateAction_Call struct {
	*mock.Call
}

// CreateAction is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - findingID string
//   - req agents.CreateActionRequest
func (_e *MockClient_Expecter) CreateAction(ctx interface{}, orgID interface{}, findingID interface{}, req interface{}) *MockClient_CreateAction_Call {
	return &MockClient_CreateAction_Call{Call: _e.mock.On("CreateAction", ctx, orgID, findingID, req)}
}

func (_c *MockClient_CreateAction_Call) Run(run func(ctx context.Context, orgID string, findingID string, req agents.CreateActionRequest)) *MockClient_CreateAction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 agents.CreateActionRequest
		if args[3] != nil {
			arg3 = args[3].(agents.CreateActionRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_CreateAction_Call) Return(createActionResponse agents.CreateActionResponse, err error) *MockClient_CreateAction_Call {
	_c.Call.Return(createActionResponse, err)
	return _c
}

func (_c *MockClient_CreateAction_Call) RunAndReturn(run func(ctx context.Context, orgID string, findingID string, req agents.CreateActionRequest) (agents.CreateActionResponse, error)) *MockClient_CreateAction_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateAction provides a mock function for the type MockClient
func (_mock *MockClient) GenerateAction(ctx context.Context, orgID string, findingID string, req agents.GenerateActionRequest) (agents.GenerateActionResponse, error) {
	ret := _mock.Called(ctx, orgID, findingID, req)

	if len(ret) == 0 {
		panic("no return value specified for GenerateAction")
	}

	var r0 agents.GenerateActionResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, agents.GenerateActionRequest) (agents.GenerateActionResponse, error)); ok {
		return returnFunc(ctx, orgID, findingID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, agents.GenerateActionRequest) agents.GenerateActionResponse); ok {
		r0 = returnFunc(ctx, orgID, findingID, req)
	} else {
		r0 = ret.Get(0).(agents.GenerateActionResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, agents.GenerateActionRequest) error); ok {
		r1 = returnFunc(ctx, orgID, findingID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GenerateAction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateAction'
type MockClient_GenerateAction_Call struct {
	*mock.Call
}

// GenerateAction is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - findingID string
//   - req agents.GenerateActionRequest
func (_e *MockClient_Expecter) GenerateAction(ctx interface{}, orgID interface{}, findingID interface{}, req interface{}) *MockClient_GenerateAction_Call {
	return &MockClient_GenerateAction_Call{Call: _e.mock.On("GenerateAction", ctx, orgID, findingID, req)}
}

func (_c *MockClient_GenerateAction_Call) Run(run func(ctx context.Context, orgID string, findingID string, req agents.GenerateActionRequest)) *MockClient_GenerateAction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 agents.GenerateActionRequest
		if args[3] != nil {
			arg3 = args[3].(agents.GenerateActionRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_GenerateAction_Call) Return(generateActionResponse agents.GenerateActionResponse, err error) *MockClient_GenerateAction_Call {
	_c.Call.Return(generateActionResponse, err)
	return _c
}

func (_c *MockClient_GenerateAction_Call) RunAndReturn(run func(ctx context.Context, orgID string, findingID string, req agents.GenerateActionRequest) (agents.GenerateActionResponse, error)) *MockClient_GenerateAction_Call {
	_c.Call.Return(run)
	return _c
}

// GetFinding provides a mock function for the type MockClient
func (_mock *MockClient) GetFinding(ctx context.Context, orgID string, findingID string) (agents.Finding, error) {
	ret := _mock.Called(ctx, orgID, findingID)

	if len(ret) == 0 {
		panic("no return value specified for GetFinding")
	}

	var r0 agents.Finding
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (agents.Finding, error)); ok {
		return returnFunc(ctx, orgID, findingID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) agents.Finding); ok {
		r0 = returnFunc(ctx, orgID, findingID)
	} else {
		r0 = ret.Get(0).(agents.Finding)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, orgID, findingID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetFinding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFinding'
type MockClient_GetFinding_Call struct {
	*mock.Call
}

// GetFinding is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - findingID string
func (_e *MockClient_Expecter) GetFinding(ctx interface{}, orgID interface{}, findingID interface{}) *MockClient_GetFinding_Call {
	return &MockClient_GetFinding_Call{Call: _e.mock.On("GetFinding", ctx, orgID, findingID)}
}

func (_c *MockClient_GetFinding_Call) Run(run func(ctx context.Context, orgID string, findingID string)) *MockClient_GetFinding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_GetFinding_Call) Return(finding agents.Finding, err error) *MockClient_GetFinding_Call {
	_c.Call.Return(finding, err)
	return _c
}

func (_c *MockClient_GetFinding_Call) RunAndReturn(run func(ctx context.Context, orgID string, findingID string) (agents.Finding, error)) *MockClient_GetFinding_Call {
	_c.Call.Return(run)
	return _c
}

// ListFindings provides a mock function for the type MockClient
func (_mock *MockClient) ListFindings(ctx context.Context, orgID string, params agents.ListFindingsParams) (agents.FindingsPage, error) {
	ret := _mock.Called(ctx, orgID, params)

	if len(ret) == 0 {
		panic("no return value specified for ListFindings")
	}

	var r0 agents.FindingsPage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, agents.ListFindingsParams) (agents.FindingsPage, error)); ok {
		return returnFunc(ctx, orgID, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, agents.ListFindingsParams) agents.FindingsPage); ok {
		r0 = returnFunc(ctx, orgID, params)
	} else {
		r0 = ret.Get(0).(agents.FindingsPage)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, agents.ListFindingsParams) error); ok {
		r1 = returnFunc(ctx, orgID, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ListFindings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFindings'
type MockClient_ListFindings_Call struct {
	*mock.Call
}

// ListFindings is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - params agents.ListFindingsParams
func (_e *MockClient_Expecter) ListFindings(ctx interface{}, orgID interface{}, params interface{}) *MockClient_ListFindings_Call {
	return &MockClient_ListFindings_Call{Call: _e.mock.On("ListFindings", ctx, orgID, params)}
}

func (_c *MockClient_ListFindings_Call) Run(run func(ctx context.Context, orgID string, params agents.ListFindingsParams)) *MockClient_ListFindings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 agents.ListFindingsParams
		if args[2] != nil {
			arg2 = args[2].(agents.ListFindingsParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_ListFindings_Call) Return(findingsPage agents.FindingsPage, err error) *MockClient_ListFindings_Call {
	_c.Call.Return(findingsPage, err)
	return _c
}

func (_c *MockClient_ListFindings_Call) RunAndReturn(run func(ctx context.Context, orgID string, params agents.ListFindingsParams) (agents.FindingsPage, error)) *MockClient_ListFindings_Call {
	_c.Call.Return(run)
	return _c
}

// ReportTask provides a mock function for the type MockClient
func (_mock *MockClient) ReportTask(ctx context.Context, orgID string, taskID string, req agents.ReportTaskRequest) (agents.ReportTaskResponse, error) {
	ret := _mock.Called(ctx, orgID, taskID, req)

	if len(ret) == 0 {
		panic("no return value specified for ReportTask")
	}

	var r0 agents.ReportTaskResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, agents.ReportTaskRequest) (agents.ReportTaskResponse, error)); ok {
		return returnFunc(ctx, orgID, taskID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, agents.ReportTaskRequest) agents.ReportTaskResponse); ok {
		r0 = returnFunc(ctx, orgID, taskID, req)
	} else {
		r0 = ret.Get(0).(agents.ReportTaskResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, agents.ReportTaskRequest) error); ok {
		r1 = returnFunc(ctx, orgID, taskID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ReportTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReportTask'
type MockClient_ReportTask_Call struct {
	*mock.Call
}

// ReportTask is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - taskID string
//   - req agents.ReportTaskRequest
func (_e *MockClient_Expecter) ReportTask(ctx interface{}, orgID interface{}, taskID interface{}, req interface{}) *MockClient_ReportTask_Call {
	return &MockClient_ReportTask_Call{Call: _e.mock.On("ReportTask", ctx, orgID, taskID, req)}
}

func (_c *MockClient_ReportTask_Call) Run(run func(ctx context.Context, orgID string, taskID string, req agents.ReportTaskRequest)) *MockClient_ReportTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 agents.ReportTaskRequest
		if args[3] != nil {
			arg3 = args[3].(agents.ReportTaskRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_ReportTask_Call) Return(reportTaskResponse agents.ReportTaskResponse, err error) *MockClient_ReportTask_Call {
	_c.Call.Return(reportTaskResponse, err)
	return _c
}

func (_c *MockClient_ReportTask_Call) RunAndReturn(run func(ctx context.Context, orgID string, taskID string, req agents.ReportTaskRequest) (agents.ReportTaskResponse, error)) *MockClient_ReportTask_Call {
	_c.Call.Return(run)
	return _c
}

// RetryAction provides a mock function for the type MockClient
func (_mock *MockClient) RetryAction(ctx context.Context, orgID string, actionID string) (agents.RetryActionResponse, error) {
	ret := _mock.Called(ctx, orgID, actionID)

	if len(ret) == 0 {
		panic("no return value specified for RetryAction")
	}

	var r0 agents.RetryActionResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (agents.RetryActionResponse, error)); ok {
		return returnFunc(ctx, orgID, actionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) agents.RetryActionResponse); ok {
		r0 = returnFunc(ctx, orgID, actionID)
	} else {
		r0 = ret.Get(0).(agents.RetryActionResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, orgID, actionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_RetryAction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetryAction'
type MockClient_RetryAction_Call struct {
	*mock.Call
}

// RetryAction is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - actionID string
func (_e *MockClient_Expecter) RetryAction(ctx interface{}, orgID interface{}, actionID interface{}) *MockClient_RetryAction_Call {
	return &MockClient_RetryAction_Call{Call: _e.mock.On("RetryAction", ctx, orgID, actionID)}
}

func (_c *MockClient_RetryAction_Call) Run(run func(ctx context.Context, orgID string, actionID string)) *MockClient_RetryAction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_RetryAction_Call) Return(retryActionResponse agents.RetryActionResponse, err error) *MockClient_RetryAction_Call {
	_c.Call.Return(retryActionResponse, err)
	return _c
}

func (_c *MockClient_RetryAction_Call) RunAndReturn(run func(ctx context.Context, orgID string, actionID string) (agents.RetryActionResponse, error)) *MockClient_RetryAction_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateFindingStatus provides a mock function for the type MockClient
func (_mock *MockClient) UpdateFindingStatus(ctx context.Context, orgID string, findingID string, req agents.UpdateFindingStatusRequest) (agents.Finding, error) {
	ret := _mock.Called(ctx, orgID, findingID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateFindingStatus")
	}

	var r0 agents.Finding
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, agents.UpdateFindingStatusRequest) (agents.Finding, error)); ok {
		return returnFunc(ctx, orgID, findingID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, agents.UpdateFindingStatusRequest) agents.Finding); ok {
		r0 = returnFunc(ctx, orgID, findingID, req)
	} else {
		r0 = ret.Get(0).(agents.Finding)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, agents.UpdateFindingStatusRequest) error); ok {
		r1 = returnFunc(ctx, orgID, findingID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_UpdateFindingStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateFindingStatus'
type MockClient_UpdateFindingStatus_Call struct {
	*mock.Call
}

// UpdateFindingStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - findingID string
//   - req agents.UpdateFindingStatusRequest
func (_e *MockClient_Expecter) UpdateFindingStatus(ctx interface{}, orgID interface{}, findingID interface{}, req interface{}) *MockClient_UpdateFindingStatus_Call {
	return &MockClient_UpdateFindingStatus_Call{Call: _e.mock.On("UpdateFindingStatus", ctx, orgID, findingID, req)}
}

func (_c *MockClient_UpdateFindingStatus_Call) Run(run func(ctx context.Context, orgID string, findingID string, req agents.UpdateFindingStatusRequest)) *MockClient_UpdateFindingStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 agents.UpdateFindingStatusRequest
		if args[3] != nil {
			arg3 = args[3].(agents.UpdateFindingStatusRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_UpdateFindingStatus_Call) Return(finding agents.Finding, err error) *MockClient_UpdateFindingStatus_Call {
	_c.Call.Return(finding, err)
	return _c
}

func (_c *MockClient_UpdateFindingStatus_Call) RunAndReturn(run func(ctx context.Context, orgID string, findingID string, req agents.UpdateFindingStatusRequest) (agents.Finding, error)) *MockClient_UpdateFindingStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTaskStatus provides a mock function for the type MockClient
func (_mock *MockClient) UpdateTaskStatus(ctx context.Context, orgID string, taskID string, req agents.UpdateTaskStatusRequest) (agents.Task, error) {
	ret := _mock.Called(ctx, orgID, taskID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTaskStatus")
	}

	var r0 agents.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, agents.UpdateTaskStatusRequest) (agents.Task, error)); ok {
		return returnFunc(ctx, orgID, taskID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, agents.UpdateTaskStatusRequest) agents.Task); ok {
		r0 = returnFunc(ctx, orgID, taskID, req)
	} else {
		r0 = ret.Get(0).(agents.Task)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, agents.UpdateTaskStatusRequest) error); ok {
		r1 = returnFunc(ctx, orgID, taskID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_UpdateTaskStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTaskStatus'
type MockClient_UpdateTaskStatus_Call struct {
	*mock.Call
}

// UpdateTaskStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - taskID string
//   - req agents.UpdateTaskStatusRequest
func (_e *MockClient_Expecter) UpdateTaskStatus(ctx interface{}, orgID interface{}, taskID interface{}, req interface{}) *MockClient_UpdateTaskStatus_Call {
	return &MockClient_UpdateTaskStatus_Call{Call: _e.mock.On("UpdateTaskStatus", ctx, orgID, taskID, req)}
}

func (_c *MockClient_UpdateTaskStatus_Call) Run(run func(ctx context.Context, orgID string, taskID string, req agents.UpdateTaskStatusRequest)) *MockClient_UpdateTaskStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 agents.UpdateTaskStatusRequest
		if args[3] != nil {
			arg3 = args[3].(agents.UpdateTaskStatusRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_UpdateTaskStatus_Call) Return(task agents.Task, err error) *MockClient_UpdateTaskStatus_Call {
	_c.Call.Return(task, err)
	return _c
}

func (_c *MockClient_UpdateTaskStatus_Call) RunAndReturn(run func(ctx context.Context, orgID string, taskID string, req agents.UpdateTaskStatusRequest) (agents.Task, error)) *MockClient_UpdateTaskStatus_Call {
	_c.Call.Return(run)
	return _c
}
