name: lint
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  golangci-lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v6
        with:
          cache: false
          go-version-file: go.mod
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.10

  mocks:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v6
        with:
          cache: false
          go-version-file: go.mod
      - run: make mocks
      - name: Check for changes
        run: |
          if [ -n "$(git diff --name-only)" ]; then
            echo "Mock files are out of date. Please run 'make mock' and commit the changes."
            git diff --name-only
            exit 1
          fi
