name: test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  unit:
    name: Unit Tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v6
        with:
          cache: false
          go-version-file: go.mod

      - uses: actions/cache/restore@v4
        with: # we only restore cache, not save it, so that PR changes don't poison it
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: nonexistent
          restore-keys: |
            ${{ runner.os }}-go-${{ hashFiles('go.mod') }}-

      - run: make test
